name: event_kampus_locator
description: Event Kampus Locator - Praktikum Servis Lokasi & Peta
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  google_maps_flutter: ^2.6.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
